server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/takwallet_db
    username: takbank
    password: takbank
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1s
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/